version: '3.8'

services:
  private-gpt:
    image: ghcr.io/zylon-ai/private-gpt:latest
    container_name: private-gpt
    ports:
      - "8001:8001"
    environment:
      - PRIVATE_GPT_SERVER_HOST=0.0.0.0
      - PRIVATE_GPT_SERVER_PORT=8001
      - PRIVATE_GPT_SERVER_CORS_ALLOW_ORIGINS=["http://localhost:8501"]
      - PRIVATE_GPT_SERVER_AUTHENTICATION_GLOBAL_ENABLED=false
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    depends_on:
      - qdrant
      - ollama
    networks:
      - email-rag-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - email-rag-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - email-rag-network

  streamlit:
    build: .
    container_name: email-rag-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./frontend:/app/frontend
    environment:
      - PRIVATE_GPT_URL=http://private-gpt:8001
      - OLLAMA_URL=http://ollama:11434
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - private-gpt
    networks:
      - email-rag-network

volumes:
  qdrant_data:
  ollama_data:

networks:
  email-rag-network:
    driver: bridge 